GET http://localhost:3014
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzQ1MzQ1MzYsImV4cCI6MTYzNDUzODEzNiwiYXVkIjoiNjE2YTY1MTM3OTIyNTViNGNlZWIzNzI5In0.g_DKZBnM4UiSGREJfIJt_FSUPWmrjW-53bPeIprnIDs



### Login Route
POST  http://localhost:3014/auth/login
Content-Type: application/json

{
    "email": "lg2h33ee@gmail.com",
    "password": "1234"
}


### Register Route
POST  http://localhost:3014/auth/register
Content-Type: application/json

{
    "email": "lg2h33ee@gmail.com",
    "password": "1234"
}


### Refresh-token Route
POST  http://localhost:3014/auth/refresh-token
Content-Type: application/json

{
     "refreashToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzQ1MzQ1MzYsImV4cCI6MTYzNDUzODEzNiwiYXVkIjoiNjE2YTY1MTM3OTIyNTViNGNlZWIzNzI5In0.g_DKZBnM4UiSGREJfIJt_FSUPWmrjW-53bPeIprnIDs"  
}


### logout Route
DELETE  http://localhost:3014/auth/logout
Content-Type: application/json

{
     "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzQ1MzM3MTYsImV4cCI6MTY2NjA5MTMxNiwiYXVkIjoiNjE2YTY1MTM3OTIyNTViNGNlZWIzNzI5In0.qLTbPRKhXYne7rzE8kHulfkrL5jRIVBC2H9J2HnD1KI"
}