GET http://localhost:3010



### Login Route
POST  http://localhost:3010/auth/login


### Register Route
POST  http://localhost:3010/auth/register
Content-Type: application/json

{
    "email": "lgh33ee@gmail.com",
    "password": "1234"
}


### Refresh-token Route
POST  http://localhost:3010/auth/refresh-token


### logout Route
DELETE  http://localhost:3010/auth/logout